name: Coverage Build
on:
  pull_request:

jobs:
  coverage:
    name: coverage build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: rolling
          # build all packages listed in the meta package
          package-name:
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_state_controller
            joint_trajectory_controller
            gripper_controllers
            position_controllers
            velocity_controllers
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/workspace.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@v1.5.0
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
