name: Build & Test ros2_controllers
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  foxy_source:
    name: Foxy source job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name: |
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_state_controller
            joint_trajectory_controller
            gripper_controllers
            position_controllers
            velocity_controllers
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/workspace.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log

  galactic_source:
    name: Galactic source job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          # build all packages listed in the meta package
          package-name: |
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_state_controller
            joint_trajectory_controller
            gripper_controllers
            position_controllers
            velocity_controllers
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/workspace.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log

  rolling_source:
    name: Rolling source job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: rolling
          # build all packages listed in the meta package
          package-name: |
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_state_controller
            joint_trajectory_controller
            gripper_controllers
            position_controllers
            velocity_controllers
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/workspace.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
